package com.talkswithtanha.twt.features.auth

import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialException
import androidx.credentials.exceptions.NoCredentialException
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential

/**
 * Google sign-in through Credential Manager.
 *
 * The old `GoogleSignInClient` / `startActivityForResult` flow is deprecated and
 * removed from recent Play Services; this is the current route and the one that
 * shows the bottom-sheet account picker rather than a full-screen activity.
 *
 * The server client id comes from `google-services.json` — the plugin generates
 * `default_web_client_id` from the OAuth client of type 3 in that file. It is
 * **not** the Android client id, and using the Android one produces a token
 * Firebase rejects with a message that does not mention which id was wrong.
 */
object GoogleSignIn {

    sealed interface Result {
        data class Success(val idToken: String) : Result
        data object Cancelled : Result
        data class Failed(val message: String) : Result
    }

    /**
     * Resolved by name rather than through `R.string.default_web_client_id`.
     *
     * That constant is generated by the Google Services plugin, which this build
     * only applies when `google-services.json` is present -- so referring to it
     * directly would stop the project compiling for anyone who has not been
     * added to the Firebase project yet. Looking it up at runtime keeps the
     * build green and turns the missing file into a sentence a developer can
     * act on.
     */
    @Suppress("DiscouragedApi")
    private fun serverClientId(context: Context): String? =
        context.resources
            .getIdentifier("default_web_client_id", "string", context.packageName)
            .takeIf { it != 0 }
            ?.let { context.getString(it) }

    suspend fun requestIdToken(context: Context): Result {
        val serverClientId = serverClientId(context)

        if (serverClientId.isNullOrBlank()) {
            // The string resource only exists once google-services.json is in
            // place. Saying that out loud beats a generic "sign-in failed" that
            // sends somebody looking at their Google account.
            return Result.Failed(
                "Google sign-in is not configured yet: app/google-services.json is missing."
            )
        }

        val option = GetGoogleIdOption.Builder()
            // False, so the picker offers every Google account on the phone
            // rather than only ones that have used this app before. A member
            // signing in on a new device has never used it before by definition.
            .setFilterByAuthorizedAccounts(false)
            .setServerClientId(serverClientId)
            .setAutoSelectEnabled(false)
            .build()

        return try {
            val response = CredentialManager.create(context).getCredential(
                context = context,
                request = GetCredentialRequest.Builder().addCredentialOption(option).build()
            )
            val credential = GoogleIdTokenCredential.createFrom(response.credential.data)
            Result.Success(credential.idToken)
        } catch (e: GetCredentialCancellationException) {
            Result.Cancelled
        } catch (e: NoCredentialException) {
            Result.Failed("No Google account on this device. Add one, or use email instead.")
        } catch (e: GetCredentialException) {
            Result.Failed(e.localizedMessage ?: "Google sign-in failed.")
        }
    }
}
